spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存相应时间，单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  thymeleaf:
    #关闭缓存
    cache: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: oyzy
    hikari:
      #连接池名
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲链接最大存活时间
      idle-timeout: 1800000
      #最大连接数
      maximum-pool-size: 10
      #自动提交
      auto-commit: true
      #链接最大存活时间，0表示永久存活
      max-lifetime: 1800000
      #链接超时时间
      connection-timeout: 30000
      #测试链接是否可用
      connection-test-query: SELECT 1

  redis:
    host: 192.168.248.131
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
#    password: root
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5



mybatis-plus:
  #配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置Mybaits数据返回类型别名
  type-aliases-package: com.oyzy.kill.pojo


#logging:
#  level:
#    com.oyzy.kill.mapper:debug
